# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  name = "Announcement"
  url = "post/2021-6-03_projectannouncement/"
  weight = 20

[[main]]
  name = "Database"
  url = "draft/database"
  weight = 25
  
[[main]]
  name = "Gemini"
  url = "gemini"
  weight = 26
  
[[main]]
  name = "People"
  url = "people"
  weight = 30

[[main]]
  name = "Events"
  url = ""
  weight = 40

[[main]]
  name = "Materials"
  url = "medium"
  weight = 50

[[main]]
  name = "Contact"
  url = "contact"
  weight = 60
